"""epic_5_class_scheduling

Revision ID: 011af93850f9
Revises: 30e9fafc9756
Create Date: 2026-02-26 08:40:24.168257

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '011af93850f9'
down_revision = '30e9fafc9756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_templates',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('default_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('default_capacity', sa.Integer(), nullable=False),
    sa.Column('class_type', sa.Enum('YOGA', 'PILATES', 'HIIT', 'CROSSFIT', 'CYCLING', 'BOXING', 'STRENGTH', 'SWIMMING', 'DANCE', 'MARTIAL_ARTS', 'OTHER', name='classtype'), nullable=False),
    sa.Column('default_instructor_staff_id', sa.Uuid(), nullable=True),
    sa.Column('default_space_id', sa.Uuid(), nullable=True),
    sa.Column('default_price_cents', sa.Integer(), nullable=False),
    sa.Column('waitlist_enabled', sa.Boolean(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_instructor_staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['default_space_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_templates_created_at'), 'class_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_class_templates_default_instructor_staff_id'), 'class_templates', ['default_instructor_staff_id'], unique=False)
    op.create_index(op.f('ix_class_templates_default_space_id'), 'class_templates', ['default_space_id'], unique=False)
    op.create_index(op.f('ix_class_templates_gym_id'), 'class_templates', ['gym_id'], unique=False)
    op.create_index(op.f('ix_class_templates_is_active'), 'class_templates', ['is_active'], unique=False)
    # Create the approvalstatus enum type before adding the column
    approvalstatus_enum = sa.Enum('AUTO_APPROVED', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', name='approvalstatus')
    approvalstatus_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('class_sessions', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    op.add_column('class_sessions', sa.Column('class_type', sa.Enum('YOGA', 'PILATES', 'HIIT', 'CROSSFIT', 'CYCLING', 'BOXING', 'STRENGTH', 'SWIMMING', 'DANCE', 'MARTIAL_ARTS', 'OTHER', name='classtype', create_type=False), nullable=True))
    op.add_column('class_sessions', sa.Column('waitlist_capacity', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('class_sessions', sa.Column('class_template_id', sa.Uuid(), nullable=True))
    op.add_column('class_sessions', sa.Column('recurrence_group_id', sa.Uuid(), nullable=True))
    op.add_column('class_sessions', sa.Column('approval_status', approvalstatus_enum, nullable=False, server_default='AUTO_APPROVED'))
    op.add_column('class_sessions', sa.Column('created_by_staff_id', sa.Uuid(), nullable=True))
    op.add_column('class_sessions', sa.Column('cancellation_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('class_sessions', sa.Column('cancelled_by_staff_id', sa.Uuid(), nullable=True))
    op.add_column('class_sessions', sa.Column('marketplace_visible', sa.Boolean(), nullable=False, server_default='true'))
    op.create_index(op.f('ix_class_sessions_class_template_id'), 'class_sessions', ['class_template_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_recurrence_group_id'), 'class_sessions', ['recurrence_group_id'], unique=False)
    op.create_foreign_key(None, 'class_sessions', 'staff', ['cancelled_by_staff_id'], ['id'])
    op.create_foreign_key(None, 'class_sessions', 'class_templates', ['class_template_id'], ['id'])
    op.create_foreign_key(None, 'class_sessions', 'staff', ['created_by_staff_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.drop_constraint(None, 'class_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_class_sessions_recurrence_group_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_class_sessions_class_template_id'), table_name='class_sessions')
    op.drop_column('class_sessions', 'marketplace_visible')
    op.drop_column('class_sessions', 'cancelled_by_staff_id')
    op.drop_column('class_sessions', 'cancellation_reason')
    op.drop_column('class_sessions', 'created_by_staff_id')
    op.drop_column('class_sessions', 'approval_status')
    op.drop_column('class_sessions', 'recurrence_group_id')
    op.drop_column('class_sessions', 'class_template_id')
    op.drop_column('class_sessions', 'waitlist_capacity')
    op.drop_column('class_sessions', 'class_type')
    op.drop_column('class_sessions', 'description')
    op.drop_index(op.f('ix_class_templates_is_active'), table_name='class_templates')
    op.drop_index(op.f('ix_class_templates_gym_id'), table_name='class_templates')
    op.drop_index(op.f('ix_class_templates_default_space_id'), table_name='class_templates')
    op.drop_index(op.f('ix_class_templates_default_instructor_staff_id'), table_name='class_templates')
    op.drop_index(op.f('ix_class_templates_created_at'), table_name='class_templates')
    op.drop_table('class_templates')
    # ### end Alembic commands ###
