"""resolve remaining schema drift

Revision ID: 30e9fafc9756
Revises: d1a2b3c4e5f6
Create Date: 2026-02-18 17:47:17.308275

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '30e9fafc9756'
down_revision = 'd1a2b3c4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('gym_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_admin_user_id'), 'audit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_gym_id'), 'audit_logs', ['gym_id'], unique=False)
    op.create_table('complaints',
    sa.Column('consumer_id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'RESOLVED', 'CLOSED', name='complaintstatus'), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('resolution', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], ),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_assigned_to'), 'complaints', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_complaints_consumer_id'), 'complaints', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_complaints_created_at'), 'complaints', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaints_gym_id'), 'complaints', ['gym_id'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('webhook_endpoints',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('secret', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_endpoints_created_at'), 'webhook_endpoints', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_endpoints_gym_id'), 'webhook_endpoints', ['gym_id'], unique=False)
    op.create_table('credit_logs',
    sa.Column('consumer_id', sa.Uuid(), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('marketplace_subscription_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['consumer_id'], ['consumers.id'], ),
    sa.ForeignKeyConstraint(['marketplace_subscription_id'], ['marketplace_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_logs_admin_user_id'), 'credit_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_credit_logs_consumer_id'), 'credit_logs', ['consumer_id'], unique=False)
    op.create_index(op.f('ix_credit_logs_created_at'), 'credit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_logs_marketplace_subscription_id'), 'credit_logs', ['marketplace_subscription_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('webhook_endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', name='webhookdeliverystatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_endpoint_id'], ['webhook_endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_created_at'), 'webhook_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_next_retry_at'), 'webhook_deliveries', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_status'), 'webhook_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_webhook_deliveries_webhook_endpoint_id'), 'webhook_deliveries', ['webhook_endpoint_id'], unique=False)
    op.create_index(op.f('ix_bookings_gym_membership_id'), 'bookings', ['gym_membership_id'], unique=False)
    op.create_index(op.f('ix_check_in_records_booking_id'), 'check_in_records', ['booking_id'], unique=False)
    op.create_index(op.f('ix_class_sessions_instructor_staff_id'), 'class_sessions', ['instructor_staff_id'], unique=False)
    op.create_index(op.f('ix_digital_waiver_acceptances_created_at'), 'digital_waiver_acceptances', ['created_at'], unique=False)
    op.drop_constraint(op.f('gym_closures_gym_id_fkey'), 'gym_closures', type_='foreignkey')
    op.create_foreign_key(None, 'gym_closures', 'gyms', ['gym_id'], ['id'])
    op.create_index(op.f('ix_gym_messages_created_at'), 'gym_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_membership_plans_created_at'), 'membership_plans', ['created_at'], unique=False)
    op.drop_constraint(op.f('notification_preferences_consumer_id_key'), 'notification_preferences', type_='unique')
    op.drop_index(op.f('ix_notification_preferences_consumer_id'), table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_consumer_id'), 'notification_preferences', ['consumer_id'], unique=True)
    op.create_index(op.f('ix_notification_preferences_created_at'), 'notification_preferences', ['created_at'], unique=False)
    op.drop_constraint(op.f('notification_templates_name_key'), 'notification_templates', type_='unique')
    op.drop_index(op.f('ix_notification_templates_name'), table_name='notification_templates')
    op.create_index(op.f('ix_notification_templates_name'), 'notification_templates', ['name'], unique=True)
    op.create_index(op.f('ix_notification_templates_created_at'), 'notification_templates', ['created_at'], unique=False)
    op.drop_index(op.f('ix_payment_receipts_id'), table_name='payment_receipts')
    op.drop_constraint(op.f('payment_receipts_payment_id_key'), 'payment_receipts', type_='unique')
    op.drop_constraint(op.f('payment_receipts_receipt_number_key'), 'payment_receipts', type_='unique')
    op.drop_index(op.f('ix_payment_receipts_payment_id'), table_name='payment_receipts')
    op.create_index(op.f('ix_payment_receipts_payment_id'), 'payment_receipts', ['payment_id'], unique=True)
    op.drop_index(op.f('ix_payment_receipts_receipt_number'), table_name='payment_receipts')
    op.create_index(op.f('ix_payment_receipts_receipt_number'), 'payment_receipts', ['receipt_number'], unique=True)
    op.drop_index(op.f('ix_payment_webhook_events_id'), table_name='payment_webhook_events')
    op.drop_constraint(op.f('payment_webhook_events_event_id_key'), 'payment_webhook_events', type_='unique')
    op.drop_index(op.f('ix_payment_webhook_events_event_id'), table_name='payment_webhook_events')
    op.create_index(op.f('ix_payment_webhook_events_event_id'), 'payment_webhook_events', ['event_id'], unique=True)
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.create_index(op.f('ix_referral_invites_class_session_id'), 'referral_invites', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_referral_invites_signed_up_consumer_id'), 'referral_invites', ['signed_up_consumer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_invites_signed_up_consumer_id'), table_name='referral_invites')
    op.drop_index(op.f('ix_referral_invites_class_session_id'), table_name='referral_invites')
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_index(op.f('ix_payment_webhook_events_event_id'), table_name='payment_webhook_events')
    op.create_index(op.f('ix_payment_webhook_events_event_id'), 'payment_webhook_events', ['event_id'], unique=False)
    op.create_unique_constraint(op.f('payment_webhook_events_event_id_key'), 'payment_webhook_events', ['event_id'])
    op.create_index(op.f('ix_payment_webhook_events_id'), 'payment_webhook_events', ['id'], unique=False)
    op.drop_index(op.f('ix_payment_receipts_receipt_number'), table_name='payment_receipts')
    op.create_index(op.f('ix_payment_receipts_receipt_number'), 'payment_receipts', ['receipt_number'], unique=False)
    op.drop_index(op.f('ix_payment_receipts_payment_id'), table_name='payment_receipts')
    op.create_index(op.f('ix_payment_receipts_payment_id'), 'payment_receipts', ['payment_id'], unique=False)
    op.create_unique_constraint(op.f('payment_receipts_receipt_number_key'), 'payment_receipts', ['receipt_number'])
    op.create_unique_constraint(op.f('payment_receipts_payment_id_key'), 'payment_receipts', ['payment_id'])
    op.create_index(op.f('ix_payment_receipts_id'), 'payment_receipts', ['id'], unique=False)
    op.drop_index(op.f('ix_notification_templates_created_at'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_name'), table_name='notification_templates')
    op.create_index(op.f('ix_notification_templates_name'), 'notification_templates', ['name'], unique=False)
    op.create_unique_constraint(op.f('notification_templates_name_key'), 'notification_templates', ['name'])
    op.drop_index(op.f('ix_notification_preferences_created_at'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_consumer_id'), table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_consumer_id'), 'notification_preferences', ['consumer_id'], unique=False)
    op.create_unique_constraint(op.f('notification_preferences_consumer_id_key'), 'notification_preferences', ['consumer_id'])
    op.drop_index(op.f('ix_membership_plans_created_at'), table_name='membership_plans')
    op.drop_index(op.f('ix_gym_messages_created_at'), table_name='gym_messages')
    op.drop_constraint(None, 'gym_closures', type_='foreignkey')
    op.create_foreign_key(op.f('gym_closures_gym_id_fkey'), 'gym_closures', 'gyms', ['gym_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_digital_waiver_acceptances_created_at'), table_name='digital_waiver_acceptances')
    op.drop_index(op.f('ix_class_sessions_instructor_staff_id'), table_name='class_sessions')
    op.drop_index(op.f('ix_check_in_records_booking_id'), table_name='check_in_records')
    op.drop_index(op.f('ix_bookings_gym_membership_id'), table_name='bookings')
    op.drop_index(op.f('ix_webhook_deliveries_webhook_endpoint_id'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_status'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_next_retry_at'), table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_created_at'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_credit_logs_marketplace_subscription_id'), table_name='credit_logs')
    op.drop_index(op.f('ix_credit_logs_created_at'), table_name='credit_logs')
    op.drop_index(op.f('ix_credit_logs_consumer_id'), table_name='credit_logs')
    op.drop_index(op.f('ix_credit_logs_admin_user_id'), table_name='credit_logs')
    op.drop_table('credit_logs')
    op.drop_index(op.f('ix_webhook_endpoints_gym_id'), table_name='webhook_endpoints')
    op.drop_index(op.f('ix_webhook_endpoints_created_at'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_gym_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_created_at'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_consumer_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_to'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_audit_logs_gym_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
