"""add_gym_consumer_space_tables

Revision ID: 35691627cac5
Revises: 1a31ce608336
Create Date: 2026-01-22 22:32:57.855954

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '35691627cac5'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumers',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=False),
    sa.Column('accepts_marketing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumers_created_at'), 'consumers', ['created_at'], unique=False)
    op.create_index(op.f('ix_consumers_email'), 'consumers', ['email'], unique=True)
    op.create_index(op.f('ix_consumers_is_active'), 'consumers', ['is_active'], unique=False)
    op.create_index(op.f('ix_consumers_phone'), 'consumers', ['phone'], unique=False)
    op.create_table('gyms',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('is_marketplace_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gyms_created_at'), 'gyms', ['created_at'], unique=False)
    op.create_index(op.f('ix_gyms_is_active'), 'gyms', ['is_active'], unique=False)
    op.create_index(op.f('ix_gyms_slug'), 'gyms', ['slug'], unique=True)
    op.create_table('spaces',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('floor_area_sqm', sa.Float(), nullable=True),
    sa.Column('has_mirrors', sa.Boolean(), nullable=False),
    sa.Column('has_sound_system', sa.Boolean(), nullable=False),
    sa.Column('has_air_conditioning', sa.Boolean(), nullable=False),
    sa.Column('is_bookable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spaces_created_at'), 'spaces', ['created_at'], unique=False)
    op.create_index(op.f('ix_spaces_gym_id'), 'spaces', ['gym_id'], unique=False)
    op.create_index(op.f('ix_spaces_is_active'), 'spaces', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spaces_is_active'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_gym_id'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_created_at'), table_name='spaces')
    op.drop_table('spaces')
    op.drop_index(op.f('ix_gyms_slug'), table_name='gyms')
    op.drop_index(op.f('ix_gyms_is_active'), table_name='gyms')
    op.drop_index(op.f('ix_gyms_created_at'), table_name='gyms')
    op.drop_table('gyms')
    op.drop_index(op.f('ix_consumers_phone'), table_name='consumers')
    op.drop_index(op.f('ix_consumers_is_active'), table_name='consumers')
    op.drop_index(op.f('ix_consumers_email'), table_name='consumers')
    op.drop_index(op.f('ix_consumers_created_at'), table_name='consumers')
    op.drop_table('consumers')
    # ### end Alembic commands ###
