"""add_social_login_fields_to_consumer

Revision ID: 3b27541620fc
Revises: e4cc4075ca9f
Create Date: 2026-01-23 19:32:37.090565

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3b27541620fc'
down_revision = 'e4cc4075ca9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumers', sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('consumers', sa.Column('apple_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # Use varchar instead of native enum for simpler handling across environments
    op.add_column('consumers', sa.Column('auth_provider', sa.String(length=20), server_default='email', nullable=False))
    op.create_index(op.f('ix_consumers_apple_id'), 'consumers', ['apple_id'], unique=True)
    op.create_index(op.f('ix_consumers_google_id'), 'consumers', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumers_google_id'), table_name='consumers')
    op.drop_index(op.f('ix_consumers_apple_id'), table_name='consumers')
    op.drop_column('consumers', 'auth_provider')
    op.drop_column('consumers', 'apple_id')
    op.drop_column('consumers', 'google_id')
    # ### end Alembic commands ###
