"""add_token_version_to_consumer_and_staff

Revision ID: 651efb3bdc08
Revises: ee64873623c4
Create Date: 2026-01-23 14:01:42.973831

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '651efb3bdc08'
down_revision = 'ee64873623c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add token_version columns with server_default for existing rows
    op.add_column('consumers', sa.Column('token_version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('staff', sa.Column('token_version', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'token_version')
    op.drop_column('consumers', 'token_version')
    # ### end Alembic commands ###
