"""add_deletion_requested_at_to_consumers

Revision ID: e4cc4075ca9f
Revises: 651efb3bdc08
Create Date: 2026-01-23 18:25:48.286303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e4cc4075ca9f'
down_revision = '651efb3bdc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumers', sa.Column('deletion_requested_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consumers', 'deletion_requested_at')
    # ### end Alembic commands ###
