"""add google_id apple_id to staff

Revision ID: e908912874a5
Revises: 011af93850f9
Create Date: 2026-02-28 10:30:59.952715

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e908912874a5'
down_revision = '011af93850f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('staff', sa.Column('apple_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_staff_apple_id'), 'staff', ['apple_id'], unique=True)
    op.create_index(op.f('ix_staff_google_id'), 'staff', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_google_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_apple_id'), table_name='staff')
    op.drop_column('staff', 'apple_id')
    op.drop_column('staff', 'google_id')
    # ### end Alembic commands ###
