"""add_staff_table

Revision ID: ee64873623c4
Revises: 769ce6b29263
Create Date: 2026-01-23 13:14:03.206128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ee64873623c4'
down_revision = '769ce6b29263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'FRONT_DESK', 'INSTRUCTOR', name='staffrole'), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_created_at'), 'staff', ['created_at'], unique=False)
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=False)
    op.create_index(op.f('ix_staff_gym_id'), 'staff', ['gym_id'], unique=False)
    op.create_index(op.f('ix_staff_is_active'), 'staff', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_is_active'), table_name='staff')
    op.drop_index(op.f('ix_staff_gym_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_index(op.f('ix_staff_created_at'), table_name='staff')
    op.drop_table('staff')
    # ### end Alembic commands ###
